version: "3.9"

networks:
  demo-ollama-network:

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  pull_policy: always
  tty: true
  restart: unless-stopped
  networks: ['demo-ollama-network']
  ports:
    - "11434:11434"
  expose:
    - 11434
  volumes:
    - ./ollama:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['demo-ollama-network']
  container_name: ollama-pull-llama
  volumes:
    - ./ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 10; OLLAMA_HOST=ollama:11434 ollama pull llama3.2; OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text"


services:

#  postgres:
#    image: postgres:latest
#    networks: [ 'demo-ollama-network' ]
#    restart: unless-stopped
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#      POSTGRES_HOST: ''
#      PGPASSWORD: postgres
#      POSTGRES_MAX_CONNECTIONS: 500
#    volumes:
#      - ./postgres_storage:/var/lib/postgresql/data
#    healthcheck:
#      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER}' ]
#      interval: 30s
#      timeout: 5s
#      retries: 3

#  qdrant:
#    image: qdrant/qdrant
#    container_name: qdrant
#    networks: [ 'demo' ]
#    restart: unless-stopped
#    ports:
#      - 6333:6333
#    volumes:
#      - ./qdrant_storage:/qdrant/storage

  ollama-cpu:
    profiles: [ "cpu" ]
    <<: *service-ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h

  ollama-gpu:
    profiles: [ "gpu-nvidia" ]
    <<: *service-ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  ollama-pull-llama-cpu:
    profiles: [ "cpu" ]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: [ "gpu-nvidia" ]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

#- driver: nvidia
#  count: all
#  capabilities: [ gpu ]